### ISSUE TITLE
Error " Fatally missing registry entries" for Forge clients in MC 1.12.2

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#171]
Because of some backward-incompatible changes in Forge between releases 13.20 (for Minecraft 1.11.2) and 14.23 (MC 1.12.2) all players using MC 1.12.2 who have Forge installed are getting the error "Fatally missing registry entries" when trying to connect to a WoL server.

This issue only applies to players using a modded client. Players with vanilla clients still can connect and play without any error.

Some background info about this issue is in [this thread at the minecraftforge forum](http://www.minecraftforge.net/forum/topic/63883-fatally-missing-registry-entries/).

A *termporary work around* for this is to install WoL also on the client.

For a mid term solution we have to consolidate all facts and decide what we could and what we want to do. There are several options I am aware of by now:
1) Don't do anything about this and just tell all players having Forge installed to also install WoL on the client.
2) Follow the idea of @diesieben07 and completely redesign the semantics and the implementation of the SpellEntity so that it is not an entity anymore but instead a listener of tick events.
3) Convince the Forge team that the new behaviour is not a feature but a bug so that it will be fixed in Forge.
4) Create some tool that will fix the bug in Forge during runtime rather than in code.
5) Migrate WoL to Bukkit
6) Just don't register the Spell entity at the Forge entity registry

**Comment by mkarneim** [comment]
I'll try to go with 6).
This will prevent the Forge server from sending the spell's entity ID to the Forge client during the login handshake.
As a side effect we can't find spell entities using selectors like "@e[type=wol:spell]" anymore.
So I'll add a new module for querying spells.

**Comment by diesieben07** [comment]
> I'll try to go with 6).
This will prevent the Forge server from sending the spell's entity ID to the Forge client during the login handshake.
As a side effect we can't find spell entities using selectors like "@e[type=wol:spell]" anymore.
So I'll add a new module for querying spells.

Oh god, please don't. This breaks things. What you have is not an entity, stop trying to make it one.

**Comment by mkarneim** [comment]
Don't bother, I have opened an [Forge issue](https://github.com/MinecraftForge/MinecraftForge/issues/4870) for this.

However, what exactly does it break?

**Comment by mkarneim** [comment]
Btw, a spell is really an entity. It is a subclass of Entity. It has a position, motion, it is ticked, it belongs to a dimension, it can be killed, it can collide, and so on. It just doesn't have a a visible representation. 
And I guess that Minecraft is perfectly fine with that. 
Also Bukkit supports custom entities, and this is server only.

**Comment by Adrodoc55** [comment]
Well as long as forge does not properly support server side entities we don't have much of a choice.

**Comment by diesieben07** [comment]
> Well as long as forge does not properly support server side entities we don't have much of a choice.

The choice is to not use an entity.

**Comment by Adrodoc55** [comment]
> a spell is really an entity. It is a subclass of Entity. It has a position, motion, it is ticked, it belongs to a dimension, it can be killed, it can collide, and so on. It just hasn't a visible representation.

Of course we can use a tick listener to reimplement the entity class, but that doesn't make much sense either. For now it seems like the easiest option to not register it as a forge entity. Of course this is an ugly work around, but writing our own entity simulator using tick listeners, because forge does not want to support server side entities would be an ugly workaround too.
The thing is Minecraft works perfectly fine with server side entities, it is just forge clients that check for the existence of the ID at startup. If the ID is not sent there (by not registering the entity or by modifying forge) minecraft is fine down the line. Not sending the entity id is also how it was handled in forge for 1.11.2, maybe we can find out why this was even changed in the first place.

**Comment by diesieben07** [comment]
Not registering it as a "forge entity" is not an option, because it breaks things left and right. Forge assigns IDs for registry entries based on the server data and data from the world. If you bypass all this you will get very weird and potentially buggy behavior.
Until Forge adds support for server-only entities, you cannot use them in Forge.

**Comment by mkarneim** [comment]
Can you please be more specific than "left and right"?

**Comment by mkarneim** [comment]
Closed. See #177.
