### ISSUE TITLE
Enhance Clipboard to support more types

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#20]
The Lua Clipboard currently supports only snapshots.

Would be nice if it supported any other Lua type as value.

**Comment by Adrodoc55** [comment]
When getting an instance of a lua class from the clipboard it is important to wrap it again using the LuaTypesRepo to make sure that the correct metatables are used at call site. The best way to handle a DelegatingTable would be to only save a reference to the delegate in the clipboard. With ImmutableTables it is a bit more tricky, because those currently have no reference to the Java object they where created from. Maybe it will be possible to look up the Java object in the lua class cache from #23.
The clipboard should cache all tables requested from it. For instances of a lua class this is done automatically in the wrapping process due to #23, for userdefined tables this caching has to be implemented in the clipboard.

**Comment by Adrodoc55** [comment]
To avoid side effects it might be a good idea to not only copy userdefined tables at request, but also when putting them into the clipboard. For instances of lua classes this is not needed, because those are either immutable or delegating and can't be modified themselfs anyway.

**Comment by mkarneim** [comment]
Just for clarification, the Clipboard exists on a per Player basis, or if you want, a per "sender" basis, to use MC/Forge terminology.
