### ISSUE TITLE
minecraft stopped after script start

### ISSUE THREAD

**Issue by SupinePandora43** [wizards-of-lua/wizards-of-lua#210]
if i start code (/lua require("printfunctest"); or command block /lua (code)) minecraft stopped(but not crashed) (mc 1.12.2,forge 14.23.5.2769, wol 2.5.0 )

**Comment by mkarneim** [comment]
Hello SupinePandora43!

Please provide some more information:

1. Did this error occur on singleplayer or multiplayer?
2. Do you have other mods installed?
3. Can please post the contents of <tt>minecraft/logs/latest.log</tt>?
4. What happens if you execute the following code:
```lua
/lua print(1)
```
5. And this:
```lua
/lua spell:execute("say hi")
```
6. What are the contents of the file "printfunctest.lua"?
7. What is the file path of your file "printfunctest.lua"? For example, it could be something like
<tt>/Users/mickkay/minecraft/config/wizards-of-lua/libs/shared/printfunctest.lua</tt>

**Comment by SupinePandora43** [comment]
1.singleplayer
2.list very looooong
3. printtest file saved in 00-000-000 without .lua, and trying to find .lua file in shared and 00-000-000 folders
4.5. 1,[Spell-4]-hi
6.just print(1)
7.C/Games/.minecraft/config/wizards-of-lua/libs/0000000-000-000-0(very long 0)/printfunctest(without .lua)

file saved without .lua and this cause error!
can you add /wol file run command and starting code from browser editor.

**Comment by mkarneim** [comment]
You should store your lua modules in files with the ".lua" extension.
Please have a look at the [tutorial about importing files from the file system](http://www.wizards-of-lua.net/tutorials/importing_lua_files/).

**Comment by SupinePandora43** [comment]
...
