### ISSUE TITLE
Add world.uuid

### ISSUE THREAD

**Issue by ShadowFoxNixill** [wizards-of-lua/wizards-of-lua#228]
The `uuid` property of a World would be a read-only unique identifier generated at the beginning of world generation. It would allow code like `pcall(require(spell.world.uuid .. "-startup"))` to create world-specific [files](229) or sections of code.

**Comment by Adrodoc** [comment]
Is [World.name](https://www.wizards-of-lua.net/modules/World/#name) not sufficient?

**Comment by ShadowFoxNixill** [comment]
`World.name` is not necessarily unique to a single world, and can be modified in-game after the world's creation.

**Comment by ShadowFoxNixill** [comment]
`World.name` is not necessarily unique to a single world, and can be modified in-game after the world's creation.

**Comment by Adrodoc** [comment]
> `World.name` is not necessarily unique to a single world, and can be modified in-game after the world's creation.

I think this is only the case for single player where you only have one world per server anyway. I think in multi player the world name has to be the name of the world folder which makes it unique for the server. I am not 100% sure about this though.

**Comment by Adrodoc** [comment]
Maybe we could add `World.directory` or `World.dir` containing the world directory path or `World.directoryName` or `World.dirName` instead of `World.uuid`.

**Comment by mkarneim** [comment]
Sadly a Minecraft world has no managed UUID.
Assigning one ourselves can't be implemented consistently, meaning we can't prevent finding multiple worlds with the same ID, e.g. when a player chooses to copy a world. This obviously breaks the "uniqueness" part of the UID concept.

Instead, a file path (absolute or even relative to some common directory) is always unique, since this is ensured by the file system itself.
But of course, it's not immutable (which I guess is another
requirement for an ID, although maybe a minor one), since files can be moved and renamed.

But at the end I guess uniqueness is more important than immutability, so I go for @Adrodoc 's idea to expose the World's directory name.

**Comment by ShadowFoxNixill** [comment]
That's fair enough. I agree with that too.

**Comment by mkarneim** [comment]
We can access the directory name via `MinecraftServer.getFolderName()`.

**Comment by Adrodoc** [comment]
@mkarneim `MinecraftServer.getFolderName()` gives us the server directory not the world directory, doesn't it?

**Comment by mkarneim** [comment]
> @mkarneim `MinecraftServer.getFolderName()` gives us the server directory not the world directory, doesn't it?

No, it's correct. `new File(server.getDataDirectory(),server.getFolderName())` gives us the complete file path to the server's world directory.
