### ISSUE TITLE
Attempting to use a formatting code precedes the change with Â

### ISSUE THREAD

**Issue by ShadowFoxNixill** [wizards-of-lua/wizards-of-lua#242]
For example, the command `/lua print("Hello there \u{A7}8Github\u{A7}r and \u{A7}9Discord\u{A7}r!")` produces in chat:
![image](https://user-images.githubusercontent.com/1627071/58768775-38f52f00-856e-11e9-8b9a-b7106b185a84.png)

The same happens if the section sign is entered directly into a UTF-8 text file.

This is a classic chacter encoding incompatibility (it's interpreting UTF-8 text as ANSI).

As a workaround: Section signs in any file saved as ANSI work properly, as well as `\xA7` instead of `\u{A7}`.

**Comment by Adrodoc** [comment]
First here are a few quotes from the specification:

1. > [The type string represents immutable sequences of bytes. Lua is 8-bit clean: strings can contain any 8-bit value, including embedded zeros ('\0'). Lua is also encoding-agnostic; it makes no assumptions about the contents of a string.](https://www.lua.org/manual/5.3/manual.html#2.1)

2. > [The UTF-8 encoding of a Unicode character can be inserted in a literal string with the escape sequence \u{XXX} (note the mandatory enclosing brackets), where XXX is a sequence of one or more hexadecimal digits representing the character code point.](https://www.lua.org/manual/5.3/manual.html#3.1)

3. > For convenience, when the opening long bracket is immediately followed by a newline, the newline is not included in the string. As an example, in a system using ASCII (in which 'a' is coded as 97, newline is coded as 10, and '1' is coded as 49), the five literal strings below denote the same string:
   > 
   >      a = 'alo\n123"'
   >      a = "alo\n123\""
   >      a = '\97lo\10\04923"'
   >      a = [[alo
   >      123"]]
   >      a = [==[
   >      alo
   >      123"]==]
   > 
   > Any byte in a literal string not explicitly affected by the previous rules represents itself. However, Lua opens files for parsing in text mode, and the system file functions may have problems with some control characters. So, it is safer to represent non-text data as a quoted literal with explicit escape sequences for the non-text characters.

The reason for the behaviour you observed is that strings are represented using the default platform encoding in rembulan. This encoding is defined via the system property `-Dfile.encoding` which in your case seems to be ANSI or ISO-8859-1.
According to the specification `\u{XXX}` does not insert a unicode character, it inserts the `UTF-8 encoding of a Unicode character`. That means that this Lua string now contains UTF-8 bytes and ANSI bytes (In your example the ANSI bytes you use are also valid UTF-8 bytes, so your string forms a valid UTF-8 string).
When we later convert this Lua string into a Java string we don't know what encoding was used to produce the bytes represented by the Lua string (remember: a Lua string represents an immutable sequence of bytes, whereas a Java string represents an immutable sequence of characters), we just know that the string is a Lua string and Lua strings are represented using the default platform encoding which is ANSI.

Instead of using `\u{A7}` or `\xA7` you really should just use `§` to be encoding-agnostic:
```lua
print("Hello there §8Github§r and §9Discord§r!")
```
