### ISSUE TITLE
1.12 version request/ item to bind spell to

### ISSUE THREAD

**Issue by CaptainKyros** [wizards-of-lua/wizards-of-lua#49]
First question: Will there be a 1.12x version of this mod
Second: If there is, will you add an item similar to [this](https://minecraft.curseforge.com/projects/generic-item-mod) to use as a spell item/"magic wand" or at least an item to use to cast spells?

**Comment by mkarneim** [comment]
Yes to both questions.
1) We migrate to 1.12 when our 1.11 version has left the beta phase, that means when all open tickets are implemented.
2) Among those open tickets are two that can be used to create a magic wand / item: #38 and #46. As the current alpha release is a complete rewrite of our feature prototype, we already know how to do this, since we have implemented it into the prototype already. We just have to port it into the alpha version. If you are curious, this is the [branch](https://github.com/wizards-of-lua/wizards-of-lua/tree/prototype). We did a lot of fun stuff with it, like a magic wand that could fire rockets, or another one that could grow huge trees. We even have made a [spell](https://gist.github.com/mkarneim/cfd15dc4a8a6d4c5bd471b62a36a126d) that gives the players world editing capabilities similar to worldedit.

**Comment by mkarneim** [comment]
Update on this: binding a spell to an item is possible since version 1.8.0-alpha.

See http://www.wizards-of-lua.net/examples/rocket-thrower/ to learn how to create a magic wand that can fire rockets, and http://www.wizards-of-lua.net/tutorials/bind-a-spell-to-a-magic-wand/ to learn how you could bind any spell directly to an item.
 
I am closing this now although we don't support MC 1.12 right now.
