### ISSUE TITLE
ClassCastException when using incorrect NBT values

### ISSUE THREAD

**Issue by Adrodoc55** [wizards-of-lua/wizards-of-lua#55]
Looking at the code it seems like there could be several ClassCastExceptions when using unexpected NBT types, for instance [here](https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/nbt/NbtConverter.java#L101).
It would be better to use something similar to the class [LuaPreconditions](https://github.com/wizards-of-lua/wizards-of-lua/blob/prototype/src/main/java/net/karneim/luamod/lua/util/LuaPreconditions.java#L16-L20) to throw an understandable Exception that includes the full path to the incorrect NBT.

**Comment by mkarneim** [comment]
Yes, good idea.

There is already a substitute of the old <tt>LuaPreconditions<tt> in the new code (see [here](https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/module/types/Types.java#L169)).

But this class is still under construction, since it is not clearly separated from the [Converters](https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/Converters.java) class.

I guess we have to refactor both, perhaps by merging them into one.
