### ISSUE TITLE
Support cancelable events

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#56]
Since most Forge events are cancelable we should think about how we could support this.

**Comment by mkarneim** [comment]
The problem is that WoL handles event asynchronously. That means, any event that happens in Minecraft is passed to its registered Lua event handlers not during the game tick, when this event occurs, but instead one game tick later. That means that it makes no sense to cancel it then (from within a Lua spell) since it  was already handled by Forge and Minecraft.

**Comment by mkarneim** [comment]
One approach could be the following: instead of having a spell to register itself for an event, we could allow a spell to register some source code.

Internally WoL would precompile the given spell and call it right when the event occurs.

The original event object would then be passed to the spell by putting it into the event's env table using the key "event".

We must ensure that the spell runs right when the event occurs, during the same game tick, and that it is not sent to sleep automatically unless it has canceled its event or called ```sleep()``` itself, what means that after this it would not be able to cancel the event anymore, and that the normal autosleep-feature is enabled again.

For any given event type a wizard could only register one single event handler.

Example: Registering a synchronous event handler for the BlockBreakEvent:
```lua
/wol event BlockBreakEvent set if event.player.name=="mickkay" then 
  event:cancel();
  spell:execute("say %s tried to break a block at %s", event.player.name, event.pos); 
end
```

To unregister this event handler:
```lua
/wol event PlayerLoggedInEvent clear
```

To inspect this event handler:
```lua
/wol event PlayerLoggedInEvent
```
This would print the event handler spell to the player's chat.

**Comment by Adrodoc55** [comment]
Only allowing a single event handler for each event type per player is a significant and unnecessary restriction. Event handlers could have an ID similar to spells. That ID could be returned by the adding command to later be used in the removal command.
Ops should also be able to remove event handlers of other players, this could be done with an optional player argument: `/wol event BlockBreakEvent clear mickkay`.
Precompiling the lua code is not just a performance optimization, but necessary to preserve the behavior of an event handler after reloading the libraries.

**Comment by mkarneim** [comment]
I have a different opinion. 
* The reason for only allowing one single 'cancelable' event handle per type and player is just a matter of simplicity. Having more handlers per type and player makes it necessary to administer them, for example by giving them IDs and commands for listing them so that you could find the right one to unregister in case you do not remember its ID. Also the execution order has to be defined somehow. It is far more easy for a player to just delegate the event to a custom function defined in a Gist, and then just editing it to add or remove event handling logic, especially when the player already has his editor open because he is editing his other codes.
* I don't think it is necessary to preserve the behavior of an event handler after reloading the libraries. 
Quite the contrary is true. By reloading the libraries the wizards are essentially 'deploying' a new release of their spells, that means that they want the new version to be in effect. Only already running spells will preserve their logic, until they are restarted, of course. But even in this case the new version will come into effect, for example when a running spell uses the <tt>spell:execute()</tt> function.

So what I suggest is that the new <tt>wol event</tt> command actually behaves exactly like the <tt>lua</tt> command in terms of reloading. The only difference is that the <tt>lua</tt> command executes its spell immediately while the <tt>wol event</tt> command executes the spell only when the respective event occurs.

**Comment by Adrodoc55** [comment]
I can agree on the second point, I just wanted to point out the difference between event queues and event handlers there, but I really dislike the restriction of only alowing a single event handler per event.
This restriction evectively prevents the use of event handlers in lua code. In my opinion it is very similar to Minecrafts [gamerule gameLoopFunction](https://minecraft.gamepedia.com/Function#Commands) which only allows a single function to be registered, but that function can then call other functions.
The problem is, that a spell can't really change the gist of the current event handler to add something dynamically.
For example imagine a spell, that makes it so you can't break blocks with some enchanted item and let something else happen instead. If you allow multiple event handlers this is easy, just add an event handler for a BlockBreakEvent that checks for the held item and cancels the event. To disable the spell just remove the event handler.
If you can only have a single event handler you'll need to update your gist that contains an event handler for all BlockBreak related spells to also call a function for your new behaviour, but now you can't enable/disable that "spell" in Minecraft, you'll always have to edit the gist.
On top of that, spells that need to cancel events under specific circumstances are harder to write. Imagine a spell that prevents you from breaking blocks when it is raining. You can use an event queue to listen to weather changes and when it starts raining you could just add a BlockBreakEventHandler that cancels all events and when the weather clears you remove the listener. This is a simple spell that can be cast from a command block and be broken seperately, but if you only allow only one event handler you need to write the spell completely different and can no longer cast it without using a gist.

**Comment by Adrodoc55** [comment]
Also I think it is very easy to assign IDs to the event handlers and provide ways for listing and removing them

**Comment by Adrodoc55** [comment]
I think the easiest way to do this is something similar to what is suggested initially:

> ```lua
> Events.on('PlayerLoggedInEvent', 'BlockBreakEvent'):run(function(event)
>   spell:say("Hello "..event.player.name.."!")
> end);
> ```
> https://github.com/wizards-of-lua/wizards-of-lua/issues/46#issuecomment-329189956

If such a function is an instance of the class Lua Function then this should be easy to implement similar to eventqueues. Each spell just keeps a reference to each function object that is registered in this way and the event forwarding can work pretty much the same as with event queues too. Because the events are handled on the same thread as the normal lua stuff we should be fine to call the registered functions directly.
If you follow the discussion following the comment I cited, you can see that the only reason we decided to use strings was due to persistence wich is necessary for a startup mechanic, but not for cancelable events.
To meet this seams like a really easy way to implement this feature,  assuming that it is easy to call a compiled lua function directly.
Calling sleep in such an event handler should probably result in an exception. 
If this implementation works it could entirely replace event queues in my opinion.

**Comment by Adrodoc55** [comment]
@mkarneim but why this limitation? It's a single threaded environment so calliing the function should be save. Also if the function is precompiled it is not affected by code changes which I think is a good thing.

**Comment by mkarneim** [comment]
This isn‘t a limitation, but a simple solution. 
You can’t just pass a function reference like that somewhere in order to call it any time later. You also would have to store the env table of the lua interpreter.
