### ISSUE TITLE
Entity.putNbt() should support setting tags

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#58]
Currently the <tt>putNbt</tt> function can't set a list of tags into an entity.

For example:
```lua
spell:putNbt({Tags={"blah"}})
```
is not working.
This only works if the spell has already at least one tag.

**Comment by Adrodoc55** [comment]
This is because it is up to wol to guess the correct NBT type for absent keys (https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/nbt/NbtConverter.java#L65-L67).
In case of a table the current strategy is to always create a new compound tag: https://github.com/wizards-of-lua/wizards-of-lua/blob/master/src/main/java/net/wizardsoflua/lua/nbt/NbtConverter.java#L177-L179
Instead you should check whether the table represents an array (whether all keys are successive integers starting at 1) and create a list tag in that case.

**Comment by mkarneim** [comment]
Alright, that sound reasonable.
