### ISSUE TITLE
Wizards should be able to break spells by tag

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#59]
For example:
```lua
/wol spell break byTag xxx
```
should break all spells that are tagged with "xxx".

This should be supported after #58 has been fixed.

**Comment by Adrodoc55** [comment]
Why support byName and byTag when you could instead just support selectors? Using selectors you could easily break spells by name/tag and have even more options like scoreboard values, position, radius, ... Since you support bySid, breaking by name is much less important, so I suggest scraping that and byTag in favor of bySelector.

**Comment by mkarneim** [comment]
As you have mentioned in #45 the use of selectors is already supported by the vanilla <tt>/kill</tt> command.

For example:
```
/kill @e[type=wol:spell,tag=mytag]
```
will break all spells tagged with "mytag".

So I think it makes no sense to copy that feature syntactically very similar into the <tt>/wol spell break</tt> command. 

The idea behind <tt>/wol spell break</tt> is to give the wizard a much simpler syntax for the most important use cases. 
However, I won't argue if you tell me that breaking a spell by tag is a rather esoteric use case.
