### ISSUE TITLE
Allow addition of new properties to existing classes like Spell

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#80]
For example: 
```lua
spell.foo="bar"
```

**Comment by Adrodoc55** [comment]
This will not be implemented, because unless we make there custom properties persistent, this would introduce inconsistent behaviour in a few scenarios:
1. If a player dies and respawns, there is a new player entity, which would loose the custom property.
1. Not entirely sure, but if an entity is unloaded and reloaded it should be a new entity too.
1. Entity proxies are cached, but only via soft references, so they may be garbage collected at any time. This means, that the custom properties may be discarded, when no reference to the corresponding table is held.
